// Code generated by MockGen. DO NOT EDIT.
// Source: data_provider.go
//
// Generated by this command:
//
//	mockgen -source=data_provider.go -destination=./testdata/data_provider.go -package=testdata
//

// Package testdata is a generated GoMock package.
package testdata

import (
	context "context"
	reflect "reflect"

	entities "github.com/parta4ok/yandex-metrics/agent/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockDataProvider is a mock of DataProvider interface.
type MockDataProvider struct {
	ctrl     *gomock.Controller
	recorder *MockDataProviderMockRecorder
	isgomock struct{}
}

// MockDataProviderMockRecorder is the mock recorder for MockDataProvider.
type MockDataProviderMockRecorder struct {
	mock *MockDataProvider
}

// NewMockDataProvider creates a new mock instance.
func NewMockDataProvider(ctrl *gomock.Controller) *MockDataProvider {
	mock := &MockDataProvider{ctrl: ctrl}
	mock.recorder = &MockDataProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataProvider) EXPECT() *MockDataProviderMockRecorder {
	return m.recorder
}

// GetActualAgentData mocks base method.
func (m *MockDataProvider) GetActualAgentData(ctx context.Context) (*entities.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActualAgentData", ctx)
	ret0, _ := ret[0].(*entities.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActualAgentData indicates an expected call of GetActualAgentData.
func (mr *MockDataProviderMockRecorder) GetActualAgentData(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActualAgentData", reflect.TypeOf((*MockDataProvider)(nil).GetActualAgentData), ctx)
}
