// Code generated by MockGen. DO NOT EDIT.
// Source: metric_service_client.go
//
// Generated by this command:
//
//	mockgen -source=metric_service_client.go -destination=./testdata/metric_service_client.go -package=testdata
//

// Package testdata is a generated GoMock package.
package testdata

import (
	context "context"
	reflect "reflect"

	entities "github.com/parta4ok/yandex-metrics/agent/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricServiceClient is a mock of MetricServiceClient interface.
type MockMetricServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockMetricServiceClientMockRecorder
	isgomock struct{}
}

// MockMetricServiceClientMockRecorder is the mock recorder for MockMetricServiceClient.
type MockMetricServiceClientMockRecorder struct {
	mock *MockMetricServiceClient
}

// NewMockMetricServiceClient creates a new mock instance.
func NewMockMetricServiceClient(ctrl *gomock.Controller) *MockMetricServiceClient {
	mock := &MockMetricServiceClient{ctrl: ctrl}
	mock.recorder = &MockMetricServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricServiceClient) EXPECT() *MockMetricServiceClientMockRecorder {
	return m.recorder
}

// UpdateAgentData mocks base method.
func (m *MockMetricServiceClient) UpdateAgentData(ctx context.Context, metric *entities.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAgentData", ctx, metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAgentData indicates an expected call of UpdateAgentData.
func (mr *MockMetricServiceClientMockRecorder) UpdateAgentData(ctx, metric any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAgentData", reflect.TypeOf((*MockMetricServiceClient)(nil).UpdateAgentData), ctx, metric)
}
