// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source=storage.go -destination=./testdata/storage.go -package=testdata
//

// Package testdata is a generated GoMock package.
package testdata

import (
	context "context"
	reflect "reflect"

	entities "github.com/parta4ok/yandex-metrics/agent/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// GetAgentData mocks base method.
func (m *MockStorage) GetAgentData(ctx context.Context) (*entities.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentData", ctx)
	ret0, _ := ret[0].(*entities.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentData indicates an expected call of GetAgentData.
func (mr *MockStorageMockRecorder) GetAgentData(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentData", reflect.TypeOf((*MockStorage)(nil).GetAgentData), ctx)
}

// SaveAgentData mocks base method.
func (m *MockStorage) SaveAgentData(ctx context.Context, metrics *entities.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAgentData", ctx, metrics)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAgentData indicates an expected call of SaveAgentData.
func (mr *MockStorageMockRecorder) SaveAgentData(ctx, metrics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAgentData", reflect.TypeOf((*MockStorage)(nil).SaveAgentData), ctx, metrics)
}
