// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=./testdata/service.go -package=testdata
//

// Package testdata is a generated GoMock package.
package testdata

import (
	context "context"
	reflect "reflect"

	entities "github.com/parta4ok/yandex-metrics/metrics/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricServiceProvider is a mock of MetricServiceProvider interface.
type MockMetricServiceProvider struct {
	ctrl     *gomock.Controller
	recorder *MockMetricServiceProviderMockRecorder
	isgomock struct{}
}

// MockMetricServiceProviderMockRecorder is the mock recorder for MockMetricServiceProvider.
type MockMetricServiceProviderMockRecorder struct {
	mock *MockMetricServiceProvider
}

// NewMockMetricServiceProvider creates a new mock instance.
func NewMockMetricServiceProvider(ctrl *gomock.Controller) *MockMetricServiceProvider {
	mock := &MockMetricServiceProvider{ctrl: ctrl}
	mock.recorder = &MockMetricServiceProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricServiceProvider) EXPECT() *MockMetricServiceProviderMockRecorder {
	return m.recorder
}

// UpdateMetric mocks base method.
func (m *MockMetricServiceProvider) UpdateMetric(ctx context.Context, metric *entities.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetric", ctx, metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetric indicates an expected call of UpdateMetric.
func (mr *MockMetricServiceProviderMockRecorder) UpdateMetric(ctx, metric any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetric", reflect.TypeOf((*MockMetricServiceProvider)(nil).UpdateMetric), ctx, metric)
}
