// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source=storage.go -destination=./testdata/storage.go -package=testdata
//

// Package testdata is a generated GoMock package.
package testdata

import (
	context "context"
	reflect "reflect"

	entities "github.com/parta4ok/yandex-metrics/metrics/internal/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockMetricsStorage is a mock of MetricsStorage interface.
type MockMetricsStorage struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsStorageMockRecorder
	isgomock struct{}
}

// MockMetricsStorageMockRecorder is the mock recorder for MockMetricsStorage.
type MockMetricsStorageMockRecorder struct {
	mock *MockMetricsStorage
}

// NewMockMetricsStorage creates a new mock instance.
func NewMockMetricsStorage(ctrl *gomock.Controller) *MockMetricsStorage {
	mock := &MockMetricsStorage{ctrl: ctrl}
	mock.recorder = &MockMetricsStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricsStorage) EXPECT() *MockMetricsStorageMockRecorder {
	return m.recorder
}

// GetMetric mocks base method.
func (m *MockMetricsStorage) GetMetric(ctx context.Context, id string, mType entities.MType) (*entities.Metric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetric", ctx, id, mType)
	ret0, _ := ret[0].(*entities.Metric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetric indicates an expected call of GetMetric.
func (mr *MockMetricsStorageMockRecorder) GetMetric(ctx, id, mType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetric", reflect.TypeOf((*MockMetricsStorage)(nil).GetMetric), ctx, id, mType)
}

// ListMetrics mocks base method.
func (m *MockMetricsStorage) ListMetrics(ctx context.Context) ([]*entities.Metric, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMetrics", ctx)
	ret0, _ := ret[0].([]*entities.Metric)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMetrics indicates an expected call of ListMetrics.
func (mr *MockMetricsStorageMockRecorder) ListMetrics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMetrics", reflect.TypeOf((*MockMetricsStorage)(nil).ListMetrics), ctx)
}

// UpdateMetric mocks base method.
func (m *MockMetricsStorage) UpdateMetric(ctx context.Context, metric *entities.Metric) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMetric", ctx, metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMetric indicates an expected call of UpdateMetric.
func (mr *MockMetricsStorageMockRecorder) UpdateMetric(ctx, metric any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMetric", reflect.TypeOf((*MockMetricsStorage)(nil).UpdateMetric), ctx, metric)
}
